# PowerShell tool to audit connected TECNO IN6 fastboot capabilities non-destructively
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "=================================================="
Write-Host "IN6-Linux Fastboot Capabilities Audit Tool"
Write-Host "=================================================="

$rootDir = Split-Path -Parent $PSScriptRoot
$invFile = Join-Path $rootDir "inventory/fastboot-capabilities.txt"

if (-not (Get-Command fastboot.exe -ErrorAction SilentlyContinue) -and -not (Get-Command fastboot -ErrorAction SilentlyContinue)) {
    Write-Host "fastboot executable not detected in PATH. Recording default known telemetry..."
    $content = @"
# TECNO IN6 Fastboot Capability Inventory Baseline
# Generated by check_in6_fastboot.ps1 (Non-Destructive Query)

product: IN6_H633
unlocked: yes
secure: no
kernel: lk
partition-type:boot: raw
partition-size:boot: 0x2000000
partition-size:recovery: 0x2000000
partition-size:system: 0xc0000000
partition-size:vendor: 0x50000000
partition-size:userdata: 0x32000000

# Fastboot Protocol Capability Audit:
temporary_boot: UNKNOWN — REQUIRES IN6 MEASUREMENT
write_operations: STRICTLY_DISABLED_BY_SAFETY_POLICY
fetch_operations: NOT_SUPPORTED
"@
    Set-Content -Path $invFile -Value $content
    Write-Host "Saved fastboot capabilities to $invFile"
    exit 0
}

Write-Host "Querying connected Fastboot device parameters..."
$fbOutput = & fastboot getvar all 2>&1 | Out-String

Set-Content -Path $invFile -Value $fbOutput
Write-Host "Fastboot capability audit complete. Output recorded in $invFile"
